### ISSUE TITLE
[patre-detail] add emergency contact info if it is given

### ISSUE THREAD

**Issue by jroedel** [Guillecaba/fathersApp#100]
Hay 6 campos que dan la información de contacto en caso que sea necesario:

- emergencyContact1Name
- emergencyContact1Relation
- emergencyContact1Phone
- emergencyContact2Name
- emergencyContact2Relation
- emergencyContact2Phone

Es mejor si sean solamente 2 ítemes en la lista de información en vez de 6.  Quizá un ejemplo puede ser:

**Emergency contact - `result["emergencyContact1Relation"]`:**
`result["emergencyContact1Name"]`
`result["emergencyContact1Phone"]`

**Emergency contact - `result["emergencyContact2Relation"]`:**
`result["emergencyContact2Name"]`
`result["emergencyContact2Phone"]`

Como esto se destina al uso en emergencia, es bueno facilitar:
1. Copiar el número
2. Llamar por whatsapp y
3. Llamar por teléfono

**Comment by Guillecaba** [comment]
en dev
