### ISSUE TITLE
[patre-detail] add bishopDate, country fields

### ISSUE THREAD

**Issue by jroedel** [Guillecaba/fathersApp#102]
bishopDate es la fecha de ordenación episcopal. Un buen ejemplo es el obispo de Encarnación, PY, personId: 344

Éstas son las traducciones de la etiqueta:
EN: Episcopal ordination
ES: Ordenación episcopal
DE: Bischofsweihe
PT: Ordenação episcopal

country es una campo string que siempre tiene 2 caracteres indicando el pais que le identifica a la persona. Sería bueno mostrar la bandera y el nombre del país. Los nombres de los paices localizados se pueden encontrar aquí: `/:lang/api/v1/interface-data["countries"]`

Etiquetas:
EN: Home country
ES: País de origen
DE: Heimatland
PT: País de origem

**Comment by Guillecaba** [comment]
En dev
