### ISSUE TITLE
[bulletin-board] mark posts 'seen' when user sees the list of bulletin board item; unbold seen items

### ISSUE THREAD

**Issue by jroedel** [Guillecaba/fathersApp#122]
Cuando el usuario mira la lista de posts, se debe llamar la API para marcarlos leídos:

`/:lang/api/v1/bulletin-board/mark-all-posts?action=seen`

Adicionalmente, se debe procurar que los posts no-leídos aparezcan en negrito; los leídos sin negrito.

**Comment by Guillecaba** [comment]
Listo
