### ISSUE TITLE
[bulletin-board] show indication in lateral menu when there is an unseen post

### ISSUE THREAD

**Issue by jroedel** [Guillecaba/fathersApp#123]
Al abrir la app o ganar focus, llama a la siguiente endpoint para averiguar si hay nuevos posts:

`/:lang/api/v1/bulletin-board/check-for-unseen-posts`

Allí se informa de manera muy sencillo si hay posts sin que el usuario los haya visto.

En caso de haber nuevos posts, informa el usuario con un círculo rojo en el menú lateral al lado derecho del texto "Recursos & noticias":

![WhatsApp Image 2020-10-03 at 4 55 30 AM](https://user-images.githubusercontent.com/3315281/94983692-b5b66580-0534-11eb-9a50-74f525680543.jpeg)

**Comment by Guillecaba** [comment]
Listo
