### ISSUE TITLE
[calendar] Make clickable space of entries bigger

### ISSUE THREAD

**Issue by jroedel** [Guillecaba/fathersApp#166]
## Objetivo
Hacerlo más fácil de hacer clic en las entidades que aparecen en el calendario. Al principio yo tenía muchos problemas para hacer clic en el calendario por que siempre picaba al lado del nombre.

## Problema
Actualmente, la caja "clicable" (donde el usuario puede hacer clic para navegar a la pantalla de esa entidad) es relativo al espacio que ocupa el texto del nombre de esa entidad.
Por ejemplo, la caja representa el espacio donde el usuario puede hacer clic:
![WhatsApp Image 2020-10-20 at 4 46 21 PM](https://user-images.githubusercontent.com/3315281/96618300-4abaac00-12f4-11eb-9625-f2d2563e2952.jpeg)

## Propuesta
Propongo que la caja clicable se extienda a la derecha lo más posible. Por ejemplo:
![WhatsApp Image 2020-10-20 at 4 46 48 PM](https://user-images.githubusercontent.com/3315281/96618825-f7952900-12f4-11eb-9c71-9c6738c8fa4a.jpeg)

**Comment by Joaquinecc** [comment]
solved
