### ISSUE TITLE
[search-persons] Crashes on iOS 14.1

### ISSUE THREAD

**Issue by jroedel** [Guillecaba/fathersApp#175]
Hace 3 días actualicé el teléfono a iOS 14.1 (desde 13.x) y dejó de funcionar la parte "Search persons". Apenas presiono el botón, se crashea la app. Hasta ahora solo he encontrado esa pantalla que crashea.

Estoy con versión 0.14

**Comment by Joaquinecc** [comment]
Puedes probar desinstalar y instalar de nuevo la app, no estoy pudiendo tener el mismo error

**Comment by jroedel** [comment]
Desinstalé y reinstalé. Se arregló. Probablemente tiene que ver con la información que estaba en el caché.

**Comment by jroedel** [comment]
Experimenté este problema de nuevo hacer una semana. Tuve que desinstalar y volver a instalar la aplicación. También recibí feedback de otro usuario que experimentó lo mismo. Se arregló de igual manera; también fue iOS.

¿Uds reciben reportes de crash de iOS? Quizá se puede ver que está causando el problema.

**Comment by Joaquinecc** [comment]
La versión 0.16 ya se soluciono el bug . Al enviar para revisión en la AppStore, nos notificaron de eso también, y nos pidieron que arreglemos.

**Comment by jroedel** [comment]
Excelente!
