### ISSUE TITLE
Combo boxes don't show selected data on Android

### ISSUE THREAD

**Issue by jroedel** [Guillecaba/fathersApp#176]
Cuando hay un elemento seleccionado en uno de los combo boxes, se pone blanco. Esto es la versión que dice "0.15" desde Expo, actualizado.

Antes de seleccionar un elemento en Filiales:

![WhatsApp Image 2020-10-25 at 5 14 43 PM](https://user-images.githubusercontent.com/3315281/97113974-acf52180-16e5-11eb-8d34-0f16cbbf0cf0.jpeg)

Después de seleccionar un elemento en Filiales:

![WhatsApp Image 2020-10-25 at 5 14 43 PM(1)](https://user-images.githubusercontent.com/3315281/97113978-b2eb0280-16e5-11eb-9073-674e41361f95.jpeg)

**Comment by Joaquinecc** [comment]
close
