### ISSUE TITLE
[living-situation-form] Add escape route when selecting in combo box

### ISSUE THREAD

**Issue by jroedel** [Guillecaba/fathersApp#177]
En iOS, cuando uno entra a seleccionar un ítem de un combo box y hay más de 7 u 8 opciones, no se puede volver sin cambiar la selección actual.

Por ejemplo, entra a modificar una situación de vivienda. Entra a seleccionar un territorio responsable. El problema es que no se puede volver sin cambiar la selección actual. Puedo anular la selección o seleccionar otro para volver, pero si no me acuerdo la selección anterior, la pierdo.

![WhatsApp Image 2020-10-25 at 5 43 47 PM](https://user-images.githubusercontent.com/3315281/97114693-e62f9080-16e9-11eb-9b0a-7e45d40ec49d.jpeg)

**Comment by Joaquinecc** [comment]
a escape route podria ser un boton cancelar abajo de todas las opciones, con color de letra rojas. si esta de acuerdo?. En android

**Comment by jroedel** [comment]
Sí, perfecto. ¿Se agregaría a todos los campos con combo box supongo?

**Comment by Joaquinecc** [comment]
OK, sin problema puedo agregar a todos

**Comment by Joaquinecc** [comment]
done
