### ISSUE TITLE
[patre-detail] 2 date fields missing

### ISSUE THREAD

**Issue by jroedel** [Guillecaba/fathersApp#178]
Nos faltan 2 campos en el detalle de las personas:

1. leaveDate ("Left the Community", "Salió de la Comunidad", "Hat die Gemeinschaft verlassen", "Saiu da Comunidade")
2. deathDate ("Passed away on", "Fallecido", "Sterbedatum", "Data do falecimento")

For example, https://schoenstatt-fathers.link/es/fathers/644

**Comment by Joaquinecc** [comment]
close
