### ISSUE TITLE
[patre-detail] Photo add button

### ISSUE THREAD

**Issue by jroedel** [Guillecaba/fathersApp#179]
Cuando la persona no tiene ninguna foto actualmente, agrega un ícono para que el usuario sepa que se puede hacer clic al lado del nombre.

Podría ser este ícono u otro que sirva: https://icons.expo.fyi/MaterialIcons/add-a-photo

![WhatsApp Image 2020-10-25 at 5 51 54 PM](https://user-images.githubusercontent.com/3315281/97114843-cba9e700-16ea-11eb-95f5-d049cadde7d9.jpeg)

**Comment by Joaquinecc** [comment]
done
