### ISSUE TITLE
[calendar] replace chalice icon

### ISSUE THREAD

**Issue by jroedel** [Guillecaba/fathersApp#187]
Hola, porfa reemplaza el ícono del cáliz con el siguiente.

![caliz-256](https://user-images.githubusercontent.com/3315281/97721033-de446780-1ac0-11eb-98e0-3467d5e2bc6c.png)

**Comment by Joaquinecc** [comment]
Te refieres al caliz que se aprecia en homescreen?
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-11-02 at 09 49 24](https://user-images.githubusercontent.com/12649261/97869722-b63b4b00-1cf0-11eb-8cb7-53eec9463025.png)

**Comment by jroedel** [comment]
Sí!

**Comment by Joaquinecc** [comment]
Done
