### ISSUE TITLE
[forms] timezone issue with Date selectors

### ISSUE THREAD

**Issue by jroedel** [Guillecaba/fathersApp#188]
Llegó un reporte del P. Francisco en Chile que no le dejaba seleccionar el 1 febrero en el selector de fecha en el formulario de las situaciones de vivienda. Sospecho que sea un problema de zona horaria. Quizá el selector sea local y el campo lo traduce a la zona UTC; algo así puede ser. 

El servidor va a interpretar la fecha en UTC, pero no va a saber cuál es la zona horaria del usuario.

Ver:
![WhatsApp Image 2020-10-28 at 12 03 56 AM](https://user-images.githubusercontent.com/3315281/97722290-64ad7900-1ac2-11eb-9caa-d9cd3acb7d9c.jpeg)
![WhatsApp Image 2020-10-28 at 12 04 08 AM](https://user-images.githubusercontent.com/3315281/97722306-68410000-1ac2-11eb-96e0-b9318cd5b0b3.jpeg)

**Comment by Joaquinecc** [comment]
Así mismo, eso es lo que sucede, como se puede ver en los screenshot esto  sucedió las 21 horas en chile y chile tiene 3 horas de diferencia con el estándar UTC, por lo cual al hacer la traducción a UTC y  obtiene las 1 am del siguiente dia. 

Estoy confundido, es necesario enviar al servidor el horario sincronizado con UTC?, porque lo que importa en esa selección de la fecha, sin importar la hora.

**Comment by jroedel** [comment]
Los datos enviados al servidor deben ser siempre un string en formato "YYYY-MM-DD" (por ejemplo "2020-11-02").

Este issue refiere a la **experiencia del usuario**. El usuario no debe tener que hacer cálculos según su relación con la zona horaria UTC. Cuando el usuario selecciona la fecha 1 de febrero de 1996, el dato enviado al servidor debe ser siempre "1996-02-01" independiente de la zona horaria en que se ubica el usuario.

**Comment by Joaquinecc** [comment]
Genial, eso me suponia. Por alguna razon se hacia la sincronizacion con UTC, pero eliminare ese comportamiento

**Comment by Joaquinecc** [comment]
Done

**Comment by jroedel** [comment]
Esto me pasó a mi de nuevo hoy a las 13:30 horario Chicago, 19:30 UTC mientras editaba un living-situation. Seleccioné el 8 de diciembre, 2020 y cuando salí del calendario decía 9 de diciembre. ¿por qué será?

![WhatsApp Image 2020-11-16 at 7 39 31 PM](https://user-images.githubusercontent.com/3315281/99300082-0dd6cc00-2844-11eb-93df-5aa9632422c5.jpeg)
![WhatsApp Image 2020-11-16 at 7 39 47 PM](https://user-images.githubusercontent.com/3315281/99300086-0fa08f80-2844-11eb-906a-ffaa593dfdb3.jpeg)

**Comment by Joaquinecc** [comment]
Que raro, no estoy seguro cual sea el problema. Igualmente modifique las funciones que utilizan UTC.
