### ISSUE TITLE
[course-detail][generation-detail][territory-detail] Add language name to ideal selector

### ISSUE THREAD

**Issue by jroedel** [Guillecaba/fathersApp#189]
Hay 3 pantallas de detalle que presentan el ideal de esa entidad en varios idiomas: el curso, la generación y el territorio. El selector en cada uno muestra el código del idioma: "en", "es", "de". Me gustaría que muestre el nombre del idioma: "English", "Spanish", "German" (localizado al idioma del usuario).

Gracias!

![WhatsApp Image 2020-10-30 at 3 17 22 PM(1)](https://user-images.githubusercontent.com/3315281/97723267-80654f00-1ac3-11eb-9767-f95e385873d1.jpeg)

**Comment by Joaquinecc** [comment]
Done
