### ISSUE TITLE
[living-situation-form] Ordered list of filiations

### ISSUE THREAD

**Issue by jroedel** [Guillecaba/fathersApp#190]
## Problema

La lista de filiales parece estar en un orden random. Esto hace dificil encontrar la filial deseada.

## Solución

Usar la lista que aparece en /api/:lang/interface-data bajo la llave "filiationOptions".

![WhatsApp Image 2020-10-30 at 3 56 10 PM](https://user-images.githubusercontent.com/3315281/97727913-d4266700-1ac8-11eb-9a4d-bc1a4ff3c2e3.jpeg)

**Comment by Joaquinecc** [comment]
Encontre el problema y es un problema hereditarios de los objetos en Js (JavaScript). Los objetos en Js si tiene keys enteras( o "int") el interprete automaticamente los ordena.

<img width="564" alt="Screen Shot 2020-11-04 at 11 48 49" src="https://user-images.githubusercontent.com/12649261/98126516-70b78300-1e94-11eb-96e7-5dd7c9850ce2.png">

 Una solucion es recibir como un array la de objetos, cons su keys. Ej:

<img width="852" alt="Screen Shot 2020-11-04 at 11 53 13" src="https://user-images.githubusercontent.com/12649261/98126580-8331bc80-1e94-11eb-8dd0-789c828f46cb.png">

**Comment by Joaquinecc** [comment]
Encontre el problema y es un problema hereditarios de los objetos en Js (JavaScript). Los objetos en Js si tiene keys enteras( o "int") el interprete automaticamente los ordena.

<img width="564" alt="Screen Shot 2020-11-04 at 11 48 49" src="https://user-images.githubusercontent.com/12649261/98126711-a8bec600-1e94-11eb-92a7-46fbd7652d38.png">


Una solucion es recibir como un array la de objetos, cons su keys. Ej:
<img width="852" alt="Screen Shot 2020-11-04 at 11 53 13" src="https://user-images.githubusercontent.com/12649261/98126728-aceae380-1e94-11eb-8ecd-b0a2fb9ff20b.png">

**Comment by Joaquinecc** [comment]
Encontre el problema y es un problema hereditarios de los objetos en Js (JavaScript). Los objetos en Js si tiene keys enteras( o "int") el interprete automaticamente los ordena.

<img width="564" alt="Screen Shot 2020-11-04 at 11 48 49" src="https://user-images.githubusercontent.com/12649261/98127093-0f43e400-1e95-11eb-9b5d-51ab4cab6523.png">

**Comment by Joaquinecc** [comment]
<img width="852" alt="Screen Shot 2020-11-04 at 11 53 13" src="https://user-images.githubusercontent.com/12649261/98126886-d6a40a80-1e94-11eb-83af-c0f5c8b177e5.png">
Una solucion es recibir como un array la de objetos, cons su keys. Ej:

**Comment by jroedel** [comment]
OK, the API has been modified:

![image](https://user-images.githubusercontent.com/3315281/98142519-cce3cc80-1ebf-11eb-80f7-2726110ce38c.png)

**Comment by Joaquinecc** [comment]
done
