### ISSUE TITLE
[living-situation-form] Ordered list of houses

### ISSUE THREAD

**Issue by jroedel** [Guillecaba/fathersApp#191]
## Problema

La lista de casas parece estar en un orden random. Esto hace dificil encontrar la casa deseada.

## Solución

Usar la lista que aparece en /api/:lang/interface-data bajo la llave "houseOptions".

![WhatsApp Image 2020-10-30 at 3 56 10 PM(1)](https://user-images.githubusercontent.com/3315281/97728030-f7511680-1ac8-11eb-92c2-02acae96e868.jpeg)

**Comment by jroedel** [comment]
The API has been modified. For example:
```
"houseOptions": [
    {
        "id": 28,
        "label": "AR Casa San Nicolás-Billinghurst",
        "sort": 0
    },
    {
        "id": 18,
        "label": "AR Córdoba",
        "sort": 1
    },
    {
        "id": 20,
        "label": "AR Florencio Varela - Casa Central",
        "sort": 2
    },
    ...
]
```

**Comment by Joaquinecc** [comment]
done
