### ISSUE TITLE
[living-situation-form] Autoselect the main house of the selected filiation

### ISSUE THREAD

**Issue by jroedel** [Guillecaba/fathersApp#192]
Para facilitar el llenado del formulario de la situación de vivienda, se sugiere lo siguiente:

A seleccionar una filial (y si todavía no se ha seleccionado una casa), autorellenar la casa según la lista /api/:lang/interface-data bajo la llave "filiationMainHouses". Esa lista mapea una filial (el filiationId) a su casa principal (houseId).

**Comment by Joaquinecc** [comment]
done
