### ISSUE TITLE
[house-detail] use formattedAddress and formattedPostAddress from API

### ISSUE THREAD

**Issue by jroedel** [Guillecaba/fathersApp#203]
El formato de la dirección cambia de país en país. En vez de formatearla desde la app, usa los campos formateados de la API: `formattedAddress`, `formattedPostAddress`.

EN: 'Address', 'Postal address'
ES: 'Domicilio', 'Dirección postal'
DE: 'Adresse', 'Postadresse'
PT: 'Endereço', 'Endereço Postal'

**Comment by Joaquinecc** [comment]
done
