### ISSUE TITLE
[patre-detail] change photo format to 3:4 aspect ratio

### ISSUE THREAD

**Issue by jroedel** [Guillecaba/fathersApp#204]
Actualmente, cuando uno hace clic a la foto de perfil, se muestra en un cuadrado (proporción 1:1). Todas las foto tienen la dimensión 150:200, ancho:alto. Ajuste la proporción a esa porfa. 

![WhatsApp Image 2020-11-10 at 5 32 38 PM](https://user-images.githubusercontent.com/3315281/98709816-c7ccc480-237a-11eb-88ea-d651cf8318ed.jpeg)

**Comment by Joaquinecc** [comment]
Done
