### ISSUE TITLE
In v1.0 Expo logo started appearing on the splash screen

### ISSUE THREAD

**Issue by jroedel** [Guillecaba/fathersApp#207]
Nunca había visto antes, pero ahora cuando abro la app desde la pantalla de inicio en Android (la app directo, no a través de Expo) y está cargando la app (mi teléfono antiguo es muy lento, tarda aprox. 5 seg.), veo el ícono de expo. ¿Por qué será?

![WhatsApp Image 2020-11-15 at 5 07 07 AM](https://user-images.githubusercontent.com/3315281/99171435-f4793700-2700-11eb-9a19-75636e5ccf7f.jpeg)

**Comment by Joaquinecc** [comment]
Done
