### ISSUE TITLE
[calendar] unknown date kinds lead to blank screen with error

### ISSUE THREAD

**Issue by jroedel** [Guillecaba/fathersApp#208]
Acerca del funcionamiento de la API de date-tiles, antes escribí:

En cuanto a la navegación, lo más importante es la propiedad `"kind"`. Eso te dice qué tipo de `"entityObject"` tenemos. Hay 4 posibilidades que necesitan navegación: `"person"`,   `"territory"`, `"course"`, `"generation"`. Además podría ser `null` o `"community"`, pero esas posibilidades no necesitan navegación.

Pienso agregar pronto fiestas litúrgicas y fechas históricas que van a tener `dateType`: `"solemnity"`, `"feast"`, `"historyDate"` pero ojalá tu código no dependa de saber todas las posibilidades.

_Originally posted by @jroedel in https://github.com/Girolabs/fathersApp/issues/98#issuecomment-688425203_

Ahora la API `/:lang/api/v1/date-tiles` entrega nuevas fechas. Éstas nuevas se tratan de entidades de tipo "event" y no deben ser navegables a ninguna otra pantalla. Actualmente cuando uno hace clic sobre estos nuevos eventos, se lleva el usuario a una pantalla blanca con un mensaje de error:
![WhatsApp Image 2020-11-15 at 5 07 13 AM](https://user-images.githubusercontent.com/3315281/99172699-ed9ef400-2701-11eb-9530-127580fde269.jpeg)
![WhatsApp Image 2020-11-15 at 5 07 16 AM](https://user-images.githubusercontent.com/3315281/99172717-eed02100-2701-11eb-83f0-61ecf5498352.jpeg)

**Comment by Joaquinecc** [comment]
Done. No deberia de haber problema en los nuevos dateTypes, sin embargo los iconos por default son los calendarios
