### ISSUE TITLE
[course-list] Only courses in generations are shown

### ISSUE THREAD

**Issue by jroedel** [Guillecaba/fathersApp#22]
Algunos cursos pertenecen a una generación pero la mayoría no. Hay que basar la lista de cursos para "Comunidad libre" en la api `/api/v1/courses`

**Comment by jroedel** [comment]
Ahora, en la versión publicada ayer en la Play Store, se ven todos los cursos pero se alistan las generaciones al revés. La primera generación debe ser Treuekreis, después Neue Gemeinschaft, como aparece en el output del endpoint

**Comment by Guillecaba** [comment]
Ok , voy a ir corrigiendo eso

**Comment by Guillecaba** [comment]
Listo
