### ISSUE TITLE
[territory-view] historical assignments shown and shouldn't by default

### ISSUE THREAD

**Issue by jroedel** [Guillecaba/fathersApp#24]
Este issue se trata de la visualización de un territorio en particular.

Un buen ejemplar is México

1. El título puede cambiarse a "Cargos" (Assignments)

2. Mostrar solamente las assignments con `"isActive": true`. En lo posible, se puede poner un botón de historia que hace aparecer toda la historial:

![Screenshot_2020-08-11 history icon at DuckDuckGo](https://user-images.githubusercontent.com/3315281/89909643-d4584a00-dbde-11ea-8251-83fac6235881.png)

**Comment by Guillecaba** [comment]
No me quedo claro, me podes adjuntar una imagen de a que se hace referencia en el punto 1

**Comment by Guillecaba** [comment]
Listo
