### ISSUE TITLE
[auth] I18n string is literal instead of constant lookup AUTH_SCREEN.SEND_EMAIL

### ISSUE THREAD

**Issue by jroedel** [Guillecaba/fathersApp#25]
Busca el texto "AUTH_SCREEN.SEND_EMAIL"

Line 56 of the AuthScreen.jsx is:

`this.setState({ hasToken: true, snackMsg: 'AUTH_SCREEN.SEND_EMAIL', visible: true, loading: false });`

and should be

`this.setState({ hasToken: true, snackMsg: i18n.t('AUTH_SCREEN.SEND_EMAIL'), visible: true, loading: false });`

**Comment by Guillecaba** [comment]
Listo
