### ISSUE TITLE
[backend] Assignments field in get Generation is empty

### ISSUE THREAD

**Issue by ALEXPY95** [Guillecaba/fathersApp#252]
En el método get "/api/v1/generations/${generationId}" para recuperar una generación, el campo "assignments" está como cadena vacía, actualmente se está usando el campo mainAssignment para obtener los cargos pero en este hay varios con el mismo nombre pero diferente valor (name, value). Tomar de referencia los métodos get de filiación, territorio y curso.

**Comment by jroedel** [comment]
Esto debe estar resuelto.
