### ISSUE TITLE
[backend] Definitions at gallery endpoints

### ISSUE THREAD

**Issue by ALEXPY95** [Guillecaba/fathersApp#253]
**En el endpoint "/api/v1/photo-gallery":** 
- el campo "commentsCount" no se actualiza según el campo "comments".

**En el endpoint `/api/v1/photo-gallery/${photoGalleryId}`:**
- el campo "comments" esta vació por mas que en el anterior endpoint ya se ve el o los comentarios.
- el campo "commentsCount" siempre esta en cero independientemente si hay comentarios o no.
- el campo "hasCurrentUserLiked" siempre esta en false independientemente si se le dio like o no.
- el campo "likesCount" siempre esta en cero independientemente si hay likes o no.

**Comment by jroedel** [comment]
Creo que está arreglado, confirma por favor
