### ISSUE TITLE
[assignment edit] Timezone confusion, DatePicker dialog doesn't match text

### ISSUE THREAD

**Issue by jroedel** [Guillecaba/fathersApp#268]
Pasos para reproducir:
1. Abre una asignación preexistente para edición (por ejemplo de un territorio). Elige una asignación que tiene fechas de inicio o término
2. Fíjate en el valor de una fecha y abre el díálogo para editarla
3. El diálogo dice el día antes de la fecha anteriormente vista. (Me imagino porque estamos hacia el occidente de UTC)

![WhatsApp Image 2022-12-27 at 11 48 36](https://user-images.githubusercontent.com/3315281/209704300-f3f6512b-956f-4855-87b6-f9528326b8b7.jpeg)
![WhatsApp Image 2022-12-27 at 11 48 49](https://user-images.githubusercontent.com/3315281/209704248-67ac3467-2f0d-43c7-83b7-b525844b6582.jpeg)

**Comment by ALEXPY95** [comment]
Este problema sigue ocurriendo? y si es asi, pasa tanto en ios como en android?

**Comment by jroedel** [comment]
Sigue ocurriendo en Android por lo menos. No se puede probar en iOS por issue #263

**Comment by angoybu** [comment]
Is this still an issue? We were not able to replicate such behavior.

**Comment by jroedel** [comment]
This seems to be fixed.
