### ISSUE TITLE
[gallery new photo] After writing a caption to a new photo, impossible to escape the keyboard

### ISSUE THREAD

**Issue by jroedel** [Guillecaba/fathersApp#276]
**Pasos para reproducir**
1. Entra a subir una nueva foto
2. Sube una foto
3. Edita la descripción
4. En iOS, el teclado tapa el texto. En Android y iOS, no se puede salir del teclado para mandar la foto
![WhatsApp Image 2022-12-29 at 18 39 03](https://user-images.githubusercontent.com/3315281/210024032-bb157110-fa53-427a-8a01-1652231afdf1.jpeg)

![WhatsApp Image 2022-12-29 at 18 42 24](https://user-images.githubusercontent.com/3315281/210024028-8fc77dcc-a0dc-45d7-bd21-39565641a8af.jpeg)

**Comment by angoybu** [comment]
@ALEXPY95 creo que falta agregar KeyboardAvoidingView

**Comment by jroedel** [comment]
Problem persists in 1.6.2
![WhatsApp Image 2022-12-30 at 16 06 09](https://user-images.githubusercontent.com/3315281/210114663-8d3ee17a-3bc7-4e5c-971e-ac47ebda7a6e.jpeg)

**Comment by ALEXPY95** [comment]
creo que es un problema con el teclado de google en ios, porque con el teclado de ios no tengo ese problema, creo que pasa lo mismo en el #262
Adjunto foto: 
![IMG_2255](https://user-images.githubusercontent.com/66885138/211897807-e735fa6d-77a0-48f7-8a8d-d395b15f4eeb.png)

**Comment by jroedel** [comment]
Appears to be fixed!
