### ISSUE TITLE
Assignments can only be added if a previous one exists

### ISSUE THREAD

**Issue by jroedel** [Guillecaba/fathersApp#280]
Example: Official community, filiation Wien. Since there are no current assignments, neither can the user add a new one. 

Please check all the screens to make sure the add assignment button appears regardless of whether there already is one:
- generation
- course
- filiation
- territory

**Comment by ALEXPY95** [comment]
ahora mostrará siempre y cuando hayan roles, hay casos como por ejemplo el curso Filii fideles donde no hay asignaciones pero tampoco hay roles, si quieren que ver la sección necesitan que el campo roles no esté vacío. Si no pongo esta condición la app se va a crashear al ver que no tiene roles para estirar en el formulario.

**Comment by jroedel** [comment]
De acuerdo!
