### ISSUE TITLE
[living situation edit create] can't remove a date once it's been set

### ISSUE THREAD

**Issue by jroedel** [Guillecaba/fathersApp#286]
No hay una manera de quitar fecha de inicio/término una vez establecida. 

![image](https://user-images.githubusercontent.com/3315281/224080778-f8cdf873-20e5-4ee5-85a5-6a0ffbe85fcf.png)

**Comment by ALEXPY95** [comment]
Hola Jeff, necesitaría permisos para poder acceder a ese formulario según tengo entendido.

**Comment by jroedel** [comment]
Fixed

**Comment by jroedel** [comment]
Fixed
