### ISSUE TITLE
[design] general navigation simplification

### ISSUE THREAD

**Issue by jroedel** [Guillecaba/fathersApp#31]
Busqué más feedback después de nuestra conversación el miércoles (12/8) y estamos de acuerdo en simplificar la navegación. La navegación es actualmente confusa para un buen porcentaje de nuestros testers y creemos que concentrar toda la navegación en la barra lateral es la mejor opción.

Consiste en lo siguiente:

- [ ] Cambiar de lado al menú lateral. Debe estar al lado derecho con un botón para abrirlo en el header de todas las pantallas
- [ ]  Suprimir el footer en todas las páginas para ganar espacio vertical. Al footer me refiero a los botones "Principal" y "Buscar" que aparece en el límite inferior de algunas pantallas
- [ ] Agregar el buscador al menú lateral de manera que aparecen las siguientes opciones: "Principal", "Buscar", "Tablón de anuncios", "Comunidad oficial", "Comunidad libre", "Cargos", "Configuraciones"
- [ ] Suprimir el botón "Tablón de anuncios" en la pantalla principal.

**Comment by Guillecaba** [comment]
listo
