### ISSUE TITLE
[calendar] Reformat the event listings

### ISSUE THREAD

**Issue by jroedel** [Guillecaba/fathersApp#45]
Propongo una reestructuración de los eventos del calendario con la siguiente intención:

1. Hacer que el nombre de la persona aparezca más grande
2. No repetir tanto las palabras "Cumpleaños" u "Onomástico"

**Propuesta concreta**: que cada evento tenga estas 4 partes:

1. Ícono que representa el tipo de evento (íconos específicos abajo)
2. Bandera del país en caso que la tengamos
3. Nombre de persona en la fuente actualmente usada para las palabras "Cumpleaños", etc

**Íconos**:

- Cumpleaños:  ![image](https://user-images.githubusercontent.com/3315281/90796672-21cf6800-e2ff-11ea-8a68-15f134603c60.png)
- Onomástico ![image](https://user-images.githubusercontent.com/3315281/90797074-aa4e0880-e2ff-11ea-8bd6-930e2399b7aa.png)
- Día de fallecimiento ![image](https://user-images.githubusercontent.com/3315281/90796779-462b4480-e2ff-11ea-8c6a-bed9310a12e7.png)
- Aniversario de ordenación ![image](https://user-images.githubusercontent.com/3315281/90797177-d23d6c00-e2ff-11ea-8073-5f86f5203f18.png)
- Otros ![image](https://user-images.githubusercontent.com/3315281/90797101-b4700700-e2ff-11ea-8bf7-7b5ca8cee48a.png)

Puede aparecer algo como el primer evento aquí:
![image](https://user-images.githubusercontent.com/3315281/90798164-1c731d00-e301-11ea-9435-73358d164d5a.png)

**Comment by jroedel** [comment]
También, sería bueno que debajo del nombre dijera cuántos años corresponde a la celebración.

**Comment by Guillecaba** [comment]
Listo en dev
