### ISSUE TITLE
[navigation] Reduce top padding on lateral menu

### ISSUE THREAD

**Issue by jroedel** [Guillecaba/fathersApp#46]
Se me comentó que en celulares con pantalla chica aparece mucho espacio en blanco encima de las palabras "Padres de Schoenstatt". Me dijo que casi no cabe todo en la pantalla por eso.

Sospecho que va a ser más claro poner el "x" para cerrar el menú al lado derecho.

![WhatsApp Image 2020-08-20 at 4 16 15 PM](https://user-images.githubusercontent.com/3315281/90798337-58a67d80-e301-11ea-93e5-d7b08e2e3a3e.jpeg)

**Comment by Guillecaba** [comment]
Listo ambos
