### ISSUE TITLE
[filiation-detail] 2 minor design issues

### ISSUE THREAD

**Issue by jroedel** [Guillecaba/fathersApp#52]
1. El color del Header1 en la pantalla FiliationDetail es raro. Debe ser el mismo color que el header2 justo debajo. El color correcto es un blanco azul. El malo es un blanco amarillento.
2. El 'roleTitle' aparece un poco corrido y no se alinea con el texto abajo. En el siguiente ejemplo, me refiero al texto "Rector" respecto al nombre "Mark Jo... Ni.."
![WhatsApp Image 2020-08-23 at 1 45 53 AM](https://user-images.githubusercontent.com/3315281/90969009-daa1cc80-e4e2-11ea-8998-faf5dbb0422b.jpeg)

**Comment by Guillecaba** [comment]
Listo
