### ISSUE TITLE
[filiation-detail] Change layout of the "Houses" section

### ISSUE THREAD

**Issue by jroedel** [Guillecaba/fathersApp#53]
Encuentro que el diseño de la lista de las casas quedó muy sobrecargado con esas cajas grandes azules. Ocupa mucho espacio para algo que no es tan importante:
![Screenshot_20200822-204144](https://user-images.githubusercontent.com/3315281/90969133-acbd8780-e4e4-11ea-8855-f8ba53a33753.png)

Propongo reformatear esa lista de casas según el modelo de la lista de filiales en la pantalla CommunityScreen con el fondo blanco y la flecha sencilla hacia el lado derecho:
![Screenshot_20200822-204159](https://user-images.githubusercontent.com/3315281/90969097-fce81a00-e4e3-11ea-8bf8-f9b37556e2bc.png)
En cuanto a la denominación "Casa principal", propongo agregar una estrella al lado derecho del nombre para indicar eso:
![Screenshot_2020-08-23  expo vector-icons directory](https://user-images.githubusercontent.com/3315281/90969127-7e3fac80-e4e4-11ea-9c80-d9b6bba399ac.png)

**Comment by Guillecaba** [comment]
en dev
