### ISSUE TITLE
[house-detail] Missing fields + open maps button

### ISSUE THREAD

**Issue by jroedel** [Guillecaba/fathersApp#54]
¿Podrías agregar 4 columnas adicionales a la pantalla HouseDetail por favor?

Faltan:
1. **Wifi password**. Propongo que aparece así `"mypassword123!" updated 5 months ago` con un boton al lado derecho para copiar la clave. 
![Screenshot_2020-08-23  expo vector-icons directory(1)](https://user-images.githubusercontent.com/3315281/90969458-8d285e00-e4e8-11ea-9c07-68a7e70139e5.png)
2. **Phones** Se pueden ir antes de `Fax`. Si una entrada tiene definido el campo `"label"` entonces se puede poner de column header, y si no, sencillamente "Phone".
  ```
  "phones": [
            {
                "label": null,
                "number": "+1 262 473-3143"
            }
        ],
  ```
3. **Public notes**
4. **Admin notes**

Example: /es/api/v1/houses/150

![Screenshot_2020-08-23 Waukesha - Patres Sion](https://user-images.githubusercontent.com/3315281/90969477-b0eba400-e4e8-11ea-858a-354585a34eb6.png)

Adicionalmente, sería muy útil tener dos botones al lado de la dirección: una para copiar la dirección al portapapeles, otra para abrir Google Maps u otro.

**Comment by jroedel** [comment]
Ahora las etiquetas del número de teléfono se traducen por la API. Por ejemplo: `/es/api/v1/houses/206`

**Comment by Guillecaba** [comment]
Listo
