### ISSUE TITLE
[person-detail] Finalize living situations

### ISSUE THREAD

**Issue by jroedel** [Guillecaba/fathersApp#55]
En la pantalla del detalle de los padres, pido unos cambios a la parte de situaciones de vivienda:
1. Arreglar "endDate", no aparece
2. Hacer que se pueda navegar a la filial, casa, o territorio desde la parte de "Situaciones de vivienda"
3. Agregar el `status` sin agregar una 6ta fila: Solo hay que mostrar el `status` en caso que no sea `'intern'`. ¿podemos agregarlo después del texto de la filial en parentesis?
Por ejemplo, está el padre # 77 que es un externo de córdoba. Entonces debajo del título "Filial" aparecería "Córdoba (externo)"
![Screenshot_2020-08-23 Fr Patres Sion](https://user-images.githubusercontent.com/3315281/90969926-0d9d8d80-e4ee-11ea-987c-6e35242dc297.png)

**Comment by Guillecaba** [comment]
Listo
