### ISSUE TITLE
[course-detail] broken back-button navigation for persons when accessed from course-detail

### ISSUE THREAD

**Issue by jroedel** [Guillecaba/fathersApp#58]
**Pasos para reproducir el problema**:

1. Abrir un curso, por ejemplo "Sanctuarium Vivum..."
2. Ir al fondo donde se alistan los miembros del curso y abre unan persona, por ejemplo "Jeff..."
3. Haz clic en el boton para "Volver atrás"

**Resultado esperado**:

Se vuelve al detalle del curso Sanctuarium Vivum

**Resultado actual**

Se vuelve a la pantalla principal.

**Comment by Guillecaba** [comment]
Listo
