### ISSUE TITLE
[course-detail] [generation-detail] [territory-detail] Find a way to display the course/generation/territory ideal statements

### ISSUE THREAD

**Issue by jroedel** [Guillecaba/fathersApp#59]
Actualmente, no se muestran las explicaciones de ideales de generación, de curso, ni de territorio. Pueden ser muy largo, así que tendría que ser una nueva pantalla creo. 

Hay 5 columnas de ideal en la API de cursos, generaciones y territorios: `enIdeal`, `esIdeal`, `deIdeal`, `ptIdeal`, `frIdeal`. A veces solo tenemos el ideal en uno o dos idiomas. La pregunta surge cómo elegir cuál de las cuatro opciones mostrar al usuario. Idealmente el usuario podría elegir entre las opciones existentes. 

Voy a agregar un campo `recommendedIdealField` que va a retornar uno de estos 6 valores: `"enIdeal"`, `"esIdeal"`, `"deIdeal"`, `"ptIdeal"`, `"frIdeal"`, `null`. Va a ser seleccionado según la localización y los campos disponibles. Agrego aquí un comentario una vez que este cambio esté realizado.

**Comment by jroedel** [comment]
Pueden suponer que los campos `enIdeal`, `esIdeal`, `deIdeal`, `ptIdeal` van a contener HTML. Actualmente es una mezcla rara entre markdown y htmlentities pero voy a arreglar eso.

**Comment by jroedel** [comment]
Actualicé los endpoints territories, courses, y generations para proveer campos para facilitar la muestra de ideales. Los campos pertinentes son los siguientes: `enIdealHtml`, `esIdealHtml`, `deIdealHtml`, `ptIdealHtml`, `frIdealHtml`, `idealLanguages`, `recommendedIdealField`. Aquí hay un ejemplo de un objecto en un LIST de cursos:
```
{
    "courseId": 69,
    "name": "SVFS",
    "celebrationDate": "20XX-10-18T00:00:00Z",
    "generationId": 12,
    "generationName": "Puente",
    "idealLanguages": {
        "en": "enIdealHtml",
        "es": "esIdealHtml",
        "de": "deIdealHtml"
    },
    "recommendedIdealField": "esIdealHtml"
}
```

El campo `recommendedIdealField` te propone un campo según la localización de la API que se está usando. El campo `esIdealHtml`, etc se retornan con el GET.

**Comment by Guillecaba** [comment]
Listo
