### ISSUE TITLE
App doesn't allow landscape orientation

### ISSUE THREAD

**Issue by jroedel** [Guillecaba/fathersApp#68]
Girando el teléfono, no gira la app. Eso sería útil específicamente para ver posts en el "Recursos y noticias"

**Comment by Guillecaba** [comment]
Listo, la orientación se puede cambiar en todas las pantallas

**Comment by jroedel** [comment]
Funciona bien en Android pero no en Apple

**Comment by angoybu** [comment]
El diseño de la aplicación no fue pensado para que la misma sea utilizada en modo horizontal, por lo cual no la habilitamos inicialmente. Si lo hacemos, será sin ningún tipo de control de calidad y no sabemos cómo puede reaccionar en distintos tamaños de pantalla y dispositivos.

Además, por el tipo de contenido que se encuentra en la sección "Recursos y Noticias", creemos que se aprovecha mejor el espacio al poner el dispositivo en modo vertical. Ej.: las oraciones por lo general están divididas en versos y estrofas, los cuales no contienen muchas palabras y tienen un salto de línea forzado. Con el dispositivo en modo horizontal, se inutiliza aproximadamente el 50% de la pantalla, a la vez de que se requiere de una mayor cantidad de deslizamientos para poder leer todo el contenido. Lo mismo ocurre con las noticias.

**Comment by jroedel** [comment]
Propongo que se habilite solo para la pantalla Bulletin Detail. ¿Esto se puede hacer?, sería muy útil para aquellos que necesitan el texto agrandado.

**Comment by Guillecaba** [comment]
Listo
