### ISSUE TITLE
[course-list] Generations are listed youngest to oldest; should be oldest to youngest

### ISSUE THREAD

**Issue by jroedel** [Guillecaba/fathersApp#70]
Ahora, en la versión publicada ayer en la Play Store, se ven todos los cursos pero se alistan las generaciones al revés. La primera generación debe ser Treuekreis, después Neue Gemeinschaft, como aparece en el output del endpoint

_Originally posted by @jroedel in https://github.com/Guillecaba/fathersApp/issues/22#issuecomment-674354143_

**Comment by Guillecaba** [comment]
Listo
