### ISSUE TITLE
Ideal statement clickable buttons are too small

### ISSUE THREAD

**Issue by jroedel** [Guillecaba/fathersApp#75]
Me gusta cómo quedó la manera que se puede seleccionar el idioma del ideal y abrir la otra página. 

Lo único es que dificulta achuntar exactamente en la pequeña flecha. Idealmente se podría hacer touch (clic) en cualquier lugar dentro de esa fila (con excepción a la selección de idioma) para avanzar a la página donde muestra el ideal.

**Comment by Guillecaba** [comment]
Listo
