### ISSUE TITLE
[generation-detail] Instead of course celebration date, show course leader

### ISSUE THREAD

**Issue by jroedel** [Guillecaba/fathersApp#76]
En las cajas que muestran los cursos que pertenecen a una generación en la pantalla **GenerationDetail**:

Actualmente, se muestra la fecha de celebración.  En verdad, esa información no es tan interesante. 

Sería mucho mejor **mostrar el jefe de curso** allí. Acabo de agregar esa información al endpoint GET generations/:id. Se encuentra en la propiedad `['courses'][]['leaderAssignment']`

**Comment by Guillecaba** [comment]
Listo
