### ISSUE TITLE
[search] The two option buttons don't show check boxes in iOS (not sure about Android)

### ISSUE THREAD

**Issue by jroedel** [Guillecaba/fathersApp#84]
Estoy mirando el "buscador" en iOS y no queda claro cómo hacer clic a las 2 opciones "Show decesed" y "Show ex-members". 

Sería bueno que aparezca claramente una caja para hacerle check.
![WhatsApp Image 2020-09-02 at 8 11 58 PM](https://user-images.githubusercontent.com/3315281/92031749-a3d87b80-ed58-11ea-8008-42aed000c1cc.jpeg)

**Comment by jroedel** [comment]
Agregué el tag "bug" porque es funcionalidad básica de la búsqueda y no queda claro al usuario cómo usarla.

**Comment by Guillecaba** [comment]
Listo
