### ISSUE TITLE
[father-form] None of the fields should be required. It seems all fields are required

### ISSUE THREAD

**Issue by jroedel** [Guillecaba/fathersApp#91]
Parece que no se puede presionar "Save" al menos que todos los campos estén ingresados. Esto no es necesario. Ningún campo es obligatorio. 
![WhatsApp Image 2020-09-02 at 8 14 57 PM](https://user-images.githubusercontent.com/3315281/92032651-05e5b080-ed5a-11ea-961f-2fb65ace564f.jpeg)

**Comment by Guillecaba** [comment]
Listo
