### ISSUE TITLE
[patre-detail] Only one phone number is shown

### ISSUE THREAD

**Issue by jroedel** [Guillecaba/fathersApp#93]
En el detalle de las personas, solo se muestra un solo número de teléfono. Un ejemplo es [persona id 362](https://schoenstatt-fathers.link/en/fathers/362).

La API entrega: 
```json
"phones": [
    {
        "number": "+52 1 444 416 0000",
        "label": "Teléfono móvil principal",
        "whatsApp": true,
        "mainCellPhone": true
    },
    {
        "number": "+593 42 290583",
        "label": "Casa"
    }
],
```

La app muestra:
![WhatsApp Image 2020-09-02 at 9 03 58 PM](https://user-images.githubusercontent.com/3315281/92036543-ec476780-ed5f-11ea-8aee-7258ff5c0608.jpeg)

De hecho, no muestra el número más importante que es su celular. Debe mostrar cada número de teléfono con la `label` entregado por la API. Preferentemente, en el mismo orden que la API.

**Comment by Guillecaba** [comment]
En review
