### ISSUE TITLE
[calendar] broken navigation to course page

### ISSUE THREAD

**Issue by jroedel** [Guillecaba/fathersApp#98]
Cuándo se hace clic en celebraciones de curso, se presenta un error.

![WhatsApp Image 2020-09-07 at 4 47 55 AM](https://user-images.githubusercontent.com/3315281/92349372-66ac1a80-f0c5-11ea-9d55-bb45823c8b49.jpeg)
![WhatsApp Image 2020-09-07 at 4 45 54 AM](https://user-images.githubusercontent.com/3315281/92349375-690e7480-f0c5-11ea-8a3b-324e664bd861.jpeg)

**Comment by Guillecaba** [comment]
Cuales son todos los casos que pueden llegar en los reminders, ademas de celebracion de cursos y todos los referentes a personas?

**Comment by jroedel** [comment]
Aquí hay un ejemplo de fecha:

```json
{
        "date": "2020-09-08T00:00:00Z",
        "dateType": "courseCelebrationDate",
        "yearsAgo": 17,
        "isImportant": false,
        "entityId": 57,
        "entityName": "United Sons of Sion",
        "entityCountry": null,
        "entityObject": {
            "courseId": 57,
            "name": "United Sons of Sion",
            "celebrationDate": "2020-09-08T00:00:00Z",
            "generationId": null,
            "generationName": null,
            "idealLanguages": {
                "en": "enIdealHtml",
                "es": "esIdealHtml",
                "de": "deIdealHtml"
            },
            "recommendedIdealField": "esIdealHtml"
        },
        "sort": 5,
        "text": "Celebración de curso",
        "showEmailButton": false,
        "kind": "course"
}
```

En cuanto a la navegación, lo más importante es la propiedad `"kind"`. Eso te dice qué tipo de `"entityObject"` tenemos. Hay 4 posibilidades que necesitan navegación: `"person"`,   `"territory"`, `"course"`, `"generation"`. Además podría ser `null` o `"community"`, pero esas posibilidades no necesitan navegación.

Pienso agregar pronto fiestas litúrgicas y fechas históricas que van a tener `dateType`: `"solemnity"`, `"feast"`, `"historyDate"` pero ojalá tu código no dependa de saber todas las posibilidades.

**Comment by Guillecaba** [comment]
Listo
